package io.microsamples.accelerator.chachkies.api

import io.microsamples.accelerator.chachkies.model.Chachkie
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity

/**
 * This file was initially generated by setting generateApiTests.set(true) in build.gradle.kts
 */
class ChachkiesChachkieTest {

    private val service: ChachkiesChachkieService = ChachkiesApiServiceImpl()
    private val api: ChachkiesChachkieController = ChachkiesChachkieController(service)

    /**
     * To test ChachkiesChachkieController.getChachkies
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    fun getChachkiesTest() {
        val response: ResponseEntity<List<Chachkie>> = api.getChachkies()

        assertThat(response.statusCode).isEqualTo(HttpStatus.OK)
        assertThat(response.body).isNotEmpty
        assertThat(response.body).hasSizeGreaterThan(0)
    }

}
